# Nombre del microservicio
spring.application.name=multas-service

# Conexion a MySQL - base de datos biblioteca_multas
# Se crea automaticamente si no existe (createDatabaseIfNotExist=true)
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca_multas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - Hibernate: actualiza automaticamente el esquema segun las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto donde corre el microservicio
server.port=8085

spring.main.web-application-type=servlet
